[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-sys-tuner"
description = "The safecoin cluster system tuner daemon"
version = "1.4.28"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = true

[dependencies]
clap = "2.33.1"
log = "0.4.8"
libc = "0.2.72"
solana-clap-utils = { path = "../clap-utils", version = "1.4.28" }
solana-logger = { path = "../logger", version = "1.4.28" }
solana-version = { path = "../version", version = "1.4.28" }

[target."cfg(unix)".dependencies]
unix_socket2 = "0.5.4"
users = "0.10.0"
nix = "0.17.0"
sysctl = "0.4.0"

[lib]
name = "solana_sys_tuner"

[[bin]]
name = "safecoin-sys-tuner"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
