[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "safecoin-net-shaper"
description = "The safecoin cluster network shaping tool"
version = "1.10.32"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
clap = "2.33.1"
rand = "0.7.0"
serde = "1.0.136"
serde_json = "1.0.79"
safecoin-logger = { path = "../logger", version = "=1.10.32" }

[[bin]]
name = "safecoin-net-shaper"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
