[package]
name = "safecoin-sdk-macro"
version = "1.15.3"
description = "Safecoin SDK Macro"
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/fair-exchange/safecoin"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-sdk-macro"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bs58 = "0.4.0"
proc-macro2 = "1.0.19"
quote = "1.0"
rustversion = "1.0.7"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
