[package]
name = "safecoin-cargo-build-bpf"
version = "1.14.3"
description = "Compile a local package and all of its dependencies using the Safecoin SBF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
homepage = "https://safecoin.org/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
cargo_metadata = "0.15.0"
clap = { version = "3.1.5", features = ["cargo", "env"] }
safecoin-sdk = { path = "..", version = "=1.14.3" }

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
