[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-local-cluster"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.9.29"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/solana-local-cluster"

[dependencies]
crossbeam-channel = "0.5"
itertools = "0.10.1"
gag = "1.0.0"
fs_extra = "1.2.0"
log = "0.4.14"
rand = "0.7.0"
rayon = "1.5.1"
safecoin-config-program = { path = "../programs/config", version = "=1.9.29" }
safecoin-core = { path = "../core", version = "=1.9.29" }
safecoin-client = { path = "../client", version = "=1.9.29" }
safecoin-download-utils = { path = "../download-utils", version = "=1.9.29" }
solana-entry = { path = "../entry", version = "=1.9.29" }
safecoin-gossip = { path = "../gossip", version = "=1.9.29" }
safecoin-ledger = { path = "../ledger", version = "=1.9.29" }
safecoin-logger = { path = "../logger", version = "=1.9.29" }
safecoin-runtime = { path = "../runtime", version = "=1.9.29" }
safecoin-sdk = { path = "../sdk", version = "=1.9.29" }
safecoin-stake-program = { path = "../programs/stake", version = "=1.9.29" }
safecoin-streamer = { path = "../streamer", version = "=1.9.29" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.9.29" }
tempfile = "3.2.0"

[dev-dependencies]
assert_matches = "1.5.0"
serial_test = "0.5.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
