[package]
name = "safecoin-bpf-loader-program"
version = "1.10.34"
description = "Safecoin BPF loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-bpf-loader-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
libsecp256k1 = "0.6.0"
log = "0.4.14"
safecoin-measure = { path = "../../measure", version = "=1.10.34" }
safecoin-metrics = { path = "../../metrics", version = "=1.10.34" }
safecoin-program-runtime = { path = "../../program-runtime", version = "=1.10.34" }
safecoin-sdk = { path = "../../sdk", version = "=1.10.34" }
safe-zk-token-sdk = { path = "../../zk-token-sdk", version = "=1.10.34" }
solana_rbpf = "=0.2.24"
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
safecoin-runtime = { path = "../../runtime", version = "=1.10.34" }

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
