[package]
name = "safecoin-bpf-loader-program"
version = "1.8.12"
description = "Safecoin BPF loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-bpf-loader-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
byteorder = "1.3.4"
log = "0.4.11"
num-derive = "0.3"
num-traits = "0.2"
rand_core = "0.6.2"
libsecp256k1 = "0.5.0"
sha3 = "0.9.1"
safecoin-measure = { path = "../../measure", version = "=1.8.12" }
safecoin-metrics = { path = "../../metrics", version = "=1.8.12" }
safecoin-runtime = { path = "../../runtime", version = "=1.8.12" }
safecoin-sdk = { path = "../../sdk", version = "=1.8.12" }
solana_rbpf = "=0.2.21"
thiserror = "1.0"

[dev-dependencies]
curve25519-dalek = "3.0.0"
rand = "0.7.3"
rustversion = "1.0.4"

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
