[package]
name = "safecoin-version"
version = "1.15.3"
description = "Safecoin Version"
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-version"
edition = "2021"

[dependencies]
log = "0.4.17"
semver = "1.0.16"
serde = "1.0.144"
serde_derive = "1.0.103"
safecoin-frozen-abi = { path = "../frozen-abi", version = "=1.15.3" }
safecoin-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.15.3" }
safecoin-sdk = { path = "../sdk", version = "=1.15.3" }

[lib]
name = "solana_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
