[package]
name = "safecoin-keygen"
version = "1.15.3"
description = "Safecoin key generation utility"
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-keygen"
edition = "2021"

[dependencies]
bs58 = "0.4.0"
clap = { version = "3.1.5", features = ["cargo"] }
dirs-next = "2.0.0"
num_cpus = "1.13.1"
safecoin-clap-v3-utils = { path = "../clap-v3-utils", version = "=1.15.3" }
safecoin-cli-config = { path = "../cli-config", version = "=1.15.3" }
safecoin-remote-wallet = { path = "../remote-wallet", version = "=1.15.3" }
safecoin-sdk = { path = "../sdk", version = "=1.15.3" }
safecoin-version = { path = "../version", version = "=1.15.3" }
tiny-bip39 = "0.8.2"

[[bin]]
name = "safecoin-keygen"
path = "src/keygen.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
