[package]
name = "solana-bpf-rust-param-passing-dep"
version = "1.6.18"
description = "Safecoin BPF program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-bpf-rust-param-passing-dep"
edition = "2018"

[dependencies]
safecoin-program = { path = "../../../../sdk/program", version = ">=1.6.18" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
