[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-validator"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.8.12"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-validator"
default-run = "safecoin-validator"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.14.1"
core_affinity = "0.5.10"
fd-lock = "2.0.0"
indicatif = "0.15.0"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils= "18.0.0"
log = "0.4.11"
num_cpus = "1.13.0"
rand = "0.7.0"
serde = "1.0.112"
serde_json = "1.0.68"
safecoin-clap-utils = { path = "../clap-utils", version = "=1.8.12" }
safecoin-cli-config = { path = "../cli-config", version = "=1.8.12" }
safecoin-client = { path = "../client", version = "=1.8.12" }
safecoin-core = { path = "../core", version = "=1.8.12" }
safecoin-download-utils = { path = "../download-utils", version = "=1.8.12" }
safecoin-faucet = { path = "../faucet", version = "=1.8.12" }
safecoin-genesis-utils = { path = "../genesis-utils", version = "=1.8.12" }
safecoin-gossip = { path = "../gossip", version = "=1.8.12" }
safecoin-ledger = { path = "../ledger", version = "=1.8.12" }
safecoin-logger = { path = "../logger", version = "=1.8.12" }
safecoin-metrics = { path = "../metrics", version = "=1.8.12" }
safecoin-net-utils = { path = "../net-utils", version = "=1.8.12" }
safecoin-perf = { path = "../perf", version = "=1.8.12" }
solana-poh = { path = "../poh", version = "=1.8.12" }
solana-rpc = { path = "../rpc", version = "=1.8.12" }
safecoin-runtime = { path = "../runtime", version = "=1.8.12" }
safecoin-sdk = { path = "../sdk", version = "=1.8.12" }
safecoin-streamer = { path = "../streamer", version = "=1.8.12" }
safecoin-version = { path = "../version", version = "=1.8.12" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.8.12" }
symlink = "0.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = {package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"]}

[target."cfg(unix)".dependencies]
libc = "0.2.81"
signal-hook = "0.1.15"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
