[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "safecoin-validator"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.14.17"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-validator"
default-run = "safecoin-validator"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
console = "0.15.0"
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
fd-lock = "3.0.5"
indicatif = "0.16.2"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc"] }
jsonrpc-derive = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-server-utils = "18.0.0"
log = "0.4.17"
num_cpus = "1.13.1"
rand = "0.7.0"
serde = "1.0.138"
serde_json = "1.0.81"
safecoin-clap-utils = { path = "../clap-utils", version = "=1.14.17" }
safecoin-cli-config = { path = "../cli-config", version = "=1.14.17" }
safecoin-client = { path = "../client", version = "=1.14.17" }
safecoin-core = { path = "../core", version = "=1.14.17" }
safecoin-download-utils = { path = "../download-utils", version = "=1.14.17" }
safecoin-entry = { path = "../entry", version = "=1.14.17" }
safecoin-faucet = { path = "../faucet", version = "=1.14.17" }
safecoin-genesis-utils = { path = "../genesis-utils", version = "=1.14.17" }
safecoin-gossip = { path = "../gossip", version = "=1.14.17" }
safecoin-ledger = { path = "../ledger", version = "=1.14.17" }
safecoin-logger = { path = "../logger", version = "=1.14.17" }
safecoin-metrics = { path = "../metrics", version = "=1.14.17" }
safecoin-net-utils = { path = "../net-utils", version = "=1.14.17" }
safecoin-perf = { path = "../perf", version = "=1.14.17" }
safecoin-poh = { path = "../poh", version = "=1.14.17" }
safecoin-rpc = { path = "../rpc", version = "=1.14.17" }
safecoin-runtime = { path = "../runtime", version = "=1.14.17" }
safecoin-sdk = { path = "../sdk", version = "=1.14.17" }
safecoin-send-transaction-service = { path = "../send-transaction-service", version = "=1.14.17" }
safecoin-storage-bigtable = { path = "../storage-bigtable", version = "=1.14.17" }
safecoin-streamer = { path = "../streamer", version = "=1.14.17" }
safecoin-test-validator = { path = "../test-validator", version = "=1.14.17" }
safecoin-version = { path = "../version", version = "=1.14.17" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.14.17" }
symlink = "0.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"] }

[target."cfg(unix)".dependencies]
libc = "0.2.126"
signal-hook = "0.3.14"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
