[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-merkle-root-bench"
version = "1.6.18"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
log = "0.4.11"
safecoin-logger = { path = "../logger", version = ">=1.6.18" }
safecoin-runtime = { path = "../runtime", version = ">=1.6.18" }
safecoin-measure = { path = "../measure", version = ">=1.6.18" }
safecoin-sdk = { path = "../sdk", version = ">=1.6.18" }
safecoin-version = { path = "../version", version = ">=1.6.18" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
