[package]
name = "safecoin-address-lookup-table-program"
version = "1.13.3"
description = "Safecoin address lookup table program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/solana-address-loookup-table-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bytemuck = "1.8.0"
log = "0.4.14"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0.136", features = ["derive"] }
safecoin-frozen-abi = { path = "../../frozen-abi", version = "=1.13.3" }
safecoin-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.13.3" }
safecoin-program = { path = "../../sdk/program", version = "=1.13.3" }
thiserror = "1.0"

[target.'cfg(not(target_arch = "bpf"))'.dependencies]
safecoin-program-runtime = { path = "../../program-runtime", version = "=1.13.3" }
safecoin-sdk = { path = "../../sdk", version = "=1.13.3" }

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "solana_address_lookup_table_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
