[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2021"
name = "safecoin-log-analyzer"
description = "The safecoin cluster network analysis tool"
version = "1.9.29"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
byte-unit = "4.0.13"
clap = "2.33.1"
serde = "1.0.130"
serde_json = "1.0.72"
safecoin-logger = { path = "../logger", version = "=1.9.29" }
safecoin-version = { path = "../version", version = "=1.9.29" }

[[bin]]
name = "safecoin-log-analyzer"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
