[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "safecoin-gossip"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.10.34"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-gossip"

[dependencies]
bincode = "1.3.3"
bv = { version = "0.11.1", features = ["serde"] }
clap = "2.33.1"
crossbeam-channel = "0.5"
flate2 = "1.0"
indexmap = { version = "1.8", features = ["rayon"] }
itertools = "0.10.3"
log = "0.4.14"
lru = "0.7.5"
matches = "0.1.9"
num-traits = "0.2"
rand = "0.7.0"
rand_chacha = "0.2.2"
rayon = "1.5.1"
serde = "1.0.136"
serde_bytes = "0.11"
serde_derive = "1.0.103"
safecoin-bloom = { path = "../bloom", version = "=1.10.34" }
safecoin-clap-utils = { path = "../clap-utils", version = "=1.10.34" }
safecoin-client = { path = "../client", version = "=1.10.34" }
solana-entry = { path = "../entry", version = "=1.10.34" }
safecoin-frozen-abi = { path = "../frozen-abi", version = "=1.10.34" }
safecoin-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.10.34" }
safecoin-ledger = { path = "../ledger", version = "=1.10.34" }
safecoin-logger = { path = "../logger", version = "=1.10.34" }
safecoin-measure = { path = "../measure", version = "=1.10.34" }
safecoin-metrics = { path = "../metrics", version = "=1.10.34" }
safecoin-net-utils = { path = "../net-utils", version = "=1.10.34" }
safecoin-perf = { path = "../perf", version = "=1.10.34" }
safecoin-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.10.34" }
safecoin-runtime = { path = "../runtime", version = "=1.10.34" }
safecoin-sdk = { path = "../sdk", version = "=1.10.34" }
safecoin-streamer = { path = "../streamer", version = "=1.10.34" }
safecoin-version = { path = "../version", version = "=1.10.35" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.10.34" }
thiserror = "1.0"

[dev-dependencies]
num_cpus = "1.13.1"
serial_test = "0.6.0"

[build-dependencies]
rustc_version = "0.4"

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bin]]
name = "safecoin-gossip"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
