[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-gossip"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.6.17"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/safecoin-gossip"

[dependencies]
clap = "2.33.1"
safecoin-clap-utils = { path = "../clap-utils", version = "=1.6.17" }
safecoin-core = { path = "../core", version = "=1.6.17" }
safecoin-logger = { path = "../logger", version = "=1.6.17" }
safecoin-net-utils = { path = "../net-utils", version = "=1.6.17" }
safecoin-sdk = { path = "../sdk", version = "=1.6.17" }
safecoin-version = { path = "../version", version = "=1.6.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
