# This package only exists to avoid circular dependencies during cargo publish:
# safecoin-bpf-loader-program -> safecoin-program-test -> safecoin-bpf-loader-program

[package]
name = "safecoin-bpf-loader-program-tests"
version = "1.14.17"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
safecoin-bpf-loader-program = { path = "../bpf_loader", version = "=1.14.17" }
safecoin-program-test = { path = "../../program-test", version = "=1.14.17" }
safecoin-sdk = { path = "../../sdk", version = "=1.14.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
