[package]
name = "solana-client-test"
version = "1.15.3"
description = "Solana RPC Test"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-client-test"
edition = "2021"
publish = false

[dependencies]
futures-util = "0.3.25"
serde_json = "1.0.83"
solana-ledger = { path = "../ledger", version = "=1.15.3" }
solana-measure = { path = "../measure", version = "=1.15.3" }
solana-merkle-tree = { path = "../merkle-tree", version = "=1.15.3" }
solana-metrics = { path = "../metrics", version = "=1.15.3" }
solana-perf = { path = "../perf", version = "=1.15.3" }
solana-pubsub-client = { path = "../pubsub-client", version = "=1.15.3" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.15.3" }
solana-rpc = { path = "../rpc", version = "=1.15.3" }
solana-rpc-client = { path = "../rpc-client", version = "=1.15.3", default-features = false }
solana-rpc-client-api = { path = "../rpc-client-api", version = "=1.15.3" }
solana-runtime = { path = "../runtime", version = "=1.15.3" }
solana-sdk = { path = "../sdk", version = "=1.15.3" }
solana-streamer = { path = "../streamer", version = "=1.15.3" }
solana-test-validator = { path = "../test-validator", version = "=1.15.3" }
solana-transaction-status = { path = "../transaction-status", version = "=1.15.3" }
solana-version = { path = "../version", version = "=1.15.3" }
systemstat = "0.2.0"
tokio = { version = "~1.14.1", features = ["full"] }
tungstenite = { version = "0.17.2", features = ["rustls-tls-webpki-roots"] }

[dev-dependencies]
solana-logger = { path = "../logger", version = "=1.15.3" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
