[package]
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
edition = "2021"
name = "safecoin-watchtower"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.15.3"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-watchtower"

[dependencies]
clap = "2.33.1"
humantime = "2.0.1"
log = "0.4.17"
safecoin-clap-utils = { path = "../clap-utils", version = "=1.15.3" }
safecoin-cli-config = { path = "../cli-config", version = "=1.15.3" }
safecoin-cli-output = { path = "../cli-output", version = "=1.15.3" }
safecoin-logger = { path = "../logger", version = "=1.15.3" }
safecoin-metrics = { path = "../metrics", version = "=1.15.3" }
safecoin-notifier = { path = "../notifier", version = "=1.15.3" }
solana-rpc-client = { path = "../rpc-client", version = "=1.15.3", default-features = false }
solana-rpc-client-api = { path = "../rpc-client-api", version = "=1.15.3" }
safecoin-sdk = { path = "../sdk", version = "=1.15.3" }
safecoin-version = { path = "../version", version = "=1.15.3" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
