[package]
name = "safecoin-tokens"
description = "Safecoin: Enterprise Security for the Community by the Community"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
version = "1.8.12"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.14.1"
csv = "1.1.3"
ctrlc = { version = "3.1.5", features = ["termination"] }
dirs-next = "2.0.0"
indexmap = "1.5.1"
indicatif = "0.15.0"
pickledb = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
safecoin-account-decoder = { path = "../account-decoder", version = "=1.8.12" }
safecoin-clap-utils = { path = "../clap-utils", version = "=1.8.12" }
safecoin-cli-config = { path = "../cli-config", version = "=1.8.12" }
safecoin-client = { path = "../client", version = "=1.8.12" }
safecoin-remote-wallet = { path = "../remote-wallet", version = "=1.8.12" }
safecoin-runtime = { path = "../runtime", version = "=1.8.12" }
safecoin-sdk = { path = "../sdk", version = "=1.8.12" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.8.12" }
safecoin-version = { path = "../version", version = "=1.8.12" }
safe-associated-token-account = { package = "safe-associated-token-account", version = "=1.0.9" }
safe-token = { version = "=3.2.2", features = ["no-entrypoint"] }
tempfile = "3.1.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.1"
safecoin-core = { path = "../core", version = "=1.8.12" }
safecoin-logger = { path = "../logger", version = "=1.8.12" }
safecoin-program-test = { path = "../program-test", version = "=1.8.12" }
safecoin-streamer = { path = "../streamer", version = "=1.8.12" }
