[package]
name = "safecoin-tokens"
description = "Safecoin: Enterprise Security for the Community by the Community"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
version = "1.14.3"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.15.0"
csv = "1.1.6"
ctrlc = { version = "3.2.2", features = ["termination"] }
indexmap = "1.9.1"
indicatif = "0.16.2"
pickledb = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
safecoin-account-decoder = { path = "../account-decoder", version = "=1.14.3" }
safecoin-clap-utils = { path = "../clap-utils", version = "=1.14.3" }
safecoin-cli-config = { path = "../cli-config", version = "=1.14.3" }
safecoin-client = { path = "../client", version = "=1.14.3" }
safecoin-remote-wallet = { path = "../remote-wallet", version = "=1.14.3" }
safecoin-sdk = { path = "../sdk", version = "=1.14.3" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.14.3" }
safecoin-version = { path = "../version", version = "=1.14.3" }
safe-associated-token-account = { version = "=1.1.1" }
safe-token = { version = "=3.5.0",  features = ["no-entrypoint"] }
tempfile = "3.3.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
safecoin-logger = { path = "../logger", version = "=1.14.3" }
safecoin-streamer = { path = "../streamer", version = "=1.14.3" }
safecoin-test-validator = { path = "../test-validator", version = "=1.14.3" }
