[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "safecoin-poh-bench"
version = "1.10.34"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-poh-bench"
publish = false

[dependencies]
clap = "2.33.1"
log = "0.4.14"
rand = "0.7.0"
rayon = "1.5.1"
solana-entry = { path = "../entry", version = "=1.10.34" }
safecoin-logger = { path = "../logger", version = "=1.10.34" }
safecoin-measure = { path = "../measure", version = "=1.10.34" }
safecoin-perf = { path = "../perf", version = "=1.10.34" }
safecoin-sdk = { path = "../sdk", version = "=1.10.34" }
safecoin-version = { path = "../version", version = "=1.10.34" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
