[package]
name = "rbpf-cli"
version = "1.9.29"
description = "CLI to test and analyze eBPF programs"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/rbpf"
homepage = "https://safecoin.org/"
keywords = ["BPF", "eBPF", "interpreter", "JIT"]
edition = "2021"
publish = false

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
serde = "1.0.130"
serde_json = "1.0.72"
safecoin-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.9.29" }
safecoin-logger = { path = "../logger", version = "=1.9.29" }
safecoin-program-runtime = { path = "../program-runtime", version = "=1.9.29" }
safecoin-sdk = { path = "../sdk", version = "=1.9.29" }
solana_rbpf = "=0.2.24"
time = "0.3.5"
