[package]
name = "rbpf-cli"
version = "1.15.3"
description = "CLI to test and analyze SBF programs"
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/rbpf"
homepage = "https://safecoin.org/"
keywords = ["SBF", "interpreter", "JIT"]
edition = "2021"
publish = false

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
serde = "1.0.144"
serde_json = "1.0.83"
safecoin-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.15.3" }
safecoin-logger = { path = "../logger", version = "=1.15.3" }
safecoin-program-runtime = { path = "../program-runtime", version = "=1.15.3" }
safecoin-sdk = { path = "../sdk", version = "=1.15.3" }
solana_rbpf = { version = "=0.2.39", features = ["debugger"] }
