[package]
name = "safecoin-ledger"
version = "1.9.29"
description = "Safecoin ledger"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-ledger"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
chrono = { version = "0.4.11", features = ["serde"] }
chrono-humanize = "0.2.1"
crossbeam-channel = "0.5"
fs_extra = "1.2.0"
futures = "0.3.17"
itertools = "0.10.1"
lazy_static = "1.4.0"
libc = "0.2.108"
log = { version = "0.4.14" }
num_cpus = "1.13.0"
num_enum = "0.5.4"
prost = "0.10.0"
rand = "0.7.0"
rand_chacha = "0.2.2"
rayon = "1.5.1"
serde = "1.0.130"
serde_bytes = "0.11.5"
sha2 = "0.9.8"
safecoin-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.9.29" }
solana-entry = { path = "../entry", version = "=1.9.29" }
safecoin-frozen-abi = { path = "../frozen-abi", version = "=1.9.29" }
safecoin-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.9.29" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.9.29" }
safecoin-logger = { path = "../logger", version = "=1.9.29" }
safecoin-measure = { path = "../measure", version = "=1.9.29" }
safecoin-metrics = { path = "../metrics", version = "=1.9.29" }
safecoin-perf = { path = "../perf", version = "=1.9.29" }
safecoin-program-runtime = { path = "../program-runtime", version = "=1.9.29" }
safecoin-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.9.29" }
safecoin-runtime = { path = "../runtime", version = "=1.9.29" }
safecoin-sdk = { path = "../sdk", version = "=1.9.29" }
safecoin-storage-bigtable = { path = "../storage-bigtable", version = "=1.9.29" }
safecoin-storage-proto = { path = "../storage-proto", version = "=1.9.29" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.9.29" }
tempfile = "3.2.0"
thiserror = "1.0"
tokio = { version = "~1.14.1", features = ["full"] }
tokio-stream = "0.1"
trees = "0.4.2"
reed-solomon-erasure = { version = "5.0.1", features = ["simd-accel"] }

[dependencies.rocksdb]
# Avoid the vendored bzip2 within rocksdb-sys that can cause linker conflicts
# when also using the bzip2 crate
git = "https://github.com/rust-rocksdb/rust-rocksdb"
branch = "master"
default-features = false
features = ["lz4","snappy"]

[dev-dependencies]
assert_matches = "1.5.0"
matches = "0.1.9"
safecoin-account-decoder = { path = "../account-decoder", version = "=1.9.29" }

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "solana_ledger"

[[bench]]
name = "sigverify_shreds"

[[bench]]
name = "blockstore"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
