[package]
name = "safecoin-storage-proto"
version = "1.15.3"
description = "Safecoin Storage Protobuf Definitions"
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-storage-proto"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
prost = "0.11.0"
serde = "1.0.144"
safecoin-account-decoder = { path = "../account-decoder", version = "=1.15.3" }
safecoin-sdk = { path = "../sdk", version = "=1.15.3" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.15.3" }

[dev-dependencies]
enum-iterator = "1.2.0"

[lib]
crate-type = ["lib"]
name = "solana_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.8.0"

# windows users should install the protobuf compiler manually and set the PROTOC
# envar to point to the installed binary
[target."cfg(not(windows))".build-dependencies]
protobuf-src = "1.0.5"
