[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-stake-monitor"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.5.8"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.1"
console = "0.11.3"
log = "0.4.11"
serde = "1.0.112"
serde_yaml = "0.8.13"
solana-clap-utils = { path = "../clap-utils", version = "1.5.8" }
solana-cli-config = { path = "../cli-config", version = "1.5.8" }
solana-client = { path = "../client", version = "1.5.8" }
solana-logger = { path = "../logger", version = "1.5.8" }
solana-metrics = { path = "../metrics", version = "1.5.8" }
solana-sdk = { path = "../sdk", version = "1.5.8" }
solana-stake-program = { path = "../programs/stake", version = "1.5.8" }
solana-transaction-status = { path = "../transaction-status", version = "1.5.8" }
solana-version = { path = "../version", version = "1.5.8" }

[dev-dependencies]
serial_test = "0.4.0"
serial_test_derive = "0.4.0"
solana-local-cluster = { path = "../local-cluster", version = "1.5.8" }
solana-core = { path = "../core", version = "1.5.8" }
tempfile = "3.1.0"

[[bin]]
name = "safecoin-stake-monitor"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
