[package]
name = "safecoin-faucet"
version = "1.5.8"
description = "Safecoin Faucet"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.3.1"
byteorder = "1.3.4"
clap = "2.33"
log = "0.4.11"
serde = "1.0.112"
serde_derive = "1.0.103"
solana-clap-utils = { path = "../clap-utils", version = "1.5.8" }
solana-cli-config = { path = "../cli-config", version = "1.5.8" }
solana-logger = { path = "../logger", version = "1.5.8" }
solana-metrics = { path = "../metrics", version = "1.5.8" }
solana-sdk = { path = "../sdk", version = "1.5.8" }
solana-version = { path = "../version", version = "1.5.8" }
tokio = { version = "0.3.5", features = ["full"] }

[lib]
crate-type = ["lib"]
name = "safecoin_faucet"

[[bin]]
name = "safecoin-faucet"
path = "src/bin/faucet.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
