[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-geyser-plugin-interface"
description = "The Safecoin Geyser plugin interface."
version = "1.9.29"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/solana-geyser-plugin-interface"

[dependencies]
log = "0.4.11"
thiserror = "1.0.30"
safecoin-sdk = { path = "../sdk", version = "=1.9.29" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
