[package]
name = "safecoin-download-utils"
version = "1.7.17"
description = "Safecoin Download Utils"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-download-utils"
edition = "2018"

[dependencies]
bzip2 = "0.3.3"
console = "0.14.1"
indicatif = "0.15.0"
log = "0.4.11"
reqwest = { version = "0.11.2", default-features = false, features = ["blocking", "rustls-tls", "json"] }
safecoin-sdk = { path = "../sdk", version = "=1.7.17" }
safecoin-runtime = { path = "../runtime", version = "=1.7.17" }
tar = "0.4.37"

[lib]
crate-type = ["lib"]
name = "solana_download_utils"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
