# This package only exists to avoid circular dependencies during cargo publish:
# safecoin-runtime -> solana-address-program-runtime -> safecoin-program-test -> safecoin-runtime

[package]
name = "solana-address-lookup-table-program-tests"
version = "1.9.29"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
solana-address-lookup-table-program = { path = "../address-lookup-table", version = "=1.9.29" }
safecoin-program-test = { path = "../../program-test", version = "=1.9.29" }
safecoin-sdk = { path = "../../sdk", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
