[package]
name = "safecoin-test-validator"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.15.3"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-test-validator"
readme = "../README.md"
repository = "https://github.com/fair-exchange/safecoin"
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
log = "0.4.17"
serde_derive = "1.0.103"
serde_json = "1.0.83"
safecoin-cli-output = { path = "../cli-output", version = "=1.15.3" }
safecoin-client = { path = "../client", version = "=1.15.3" }
safecoin-core = { path = "../core", version = "=1.15.3" }
safecoin-gossip = { path = "../gossip", version = "=1.15.3" }
safecoin-ledger = { path = "../ledger", version = "=1.15.3" }
safecoin-logger = { path = "../logger", version = "=1.15.3" }
safecoin-net-utils = { path = "../net-utils", version = "=1.15.3" }
safecoin-program-runtime = { path = "../program-runtime", version = "=1.15.3" }
safecoin-program-test = { path = "../program-test", version = "=1.15.3" }
safecoin-rpc = { path = "../rpc", version = "=1.15.3" }
safecoin-rpc-client = { path = "../rpc-client", version = "=1.15.3", default-features = false }
safecoin-runtime = { path = "../runtime", version = "=1.15.3" }
safecoin-sdk = { path = "../sdk", version = "=1.15.3" }
safecoin-streamer = { path = "../streamer", version = "=1.15.3" }
safecoin-tpu-client = { path = "../tpu-client", version = "=1.15.3", default-features = false }
tokio = { version = "1", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
