[package]
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
edition = "2021"
name = "safecoin-install"
description = "The safecoin cluster software installer"
version = "1.15.3"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-install"

[dependencies]
atty = "0.2.11"
bincode = "1.3.3"
bzip2 = "0.4.4"
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "2.33.1" }
console = "0.15.0"
crossbeam-channel = "0.5"
ctrlc = { version = "3.2.3", features = ["termination"] }
dirs-next = "2.0.0"
indicatif = "0.17.1"
lazy_static = "1.4.0"
nix = "0.25.0"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
scopeguard = "1.1.0"
semver = "1.0.16"
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.9.13"
serde_yaml_08 = { package = "serde_yaml", version = "0.8.26" }
safecoin-clap-utils = { path = "../clap-utils", version = "=1.15.3" }
safecoin-config-program = { path = "../programs/config", version = "=1.15.3" }
safecoin-logger = { path = "../logger", version = "=1.15.3" }
safecoin-rpc-client = { path = "../rpc-client", version = "=1.15.3", default-features = false }
safecoin-sdk = { path = "../sdk", version = "=1.15.3" }
safecoin-version = { path = "../version", version = "=1.15.3" }
tar = "0.4.38"
tempfile = "3.3.0"
url = "2.2.2"

[target."cfg(windows)".dependencies]
winapi = "0.3.8"
winreg = "0.10"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
