[package]
name = "solana-rpc-test"
version = "1.10.34"
description = "Safecoin RPC Test"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/solana-rpc-test"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
futures-util = "0.3.21"
log = "0.4.11"
reqwest = { version = "0.11.10", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde = "1.0.136"
serde_json = "1.0.79"
safecoin-account-decoder = { path = "../account-decoder", version = "=1.10.34" }
safecoin-client = { path = "../client", version = "=1.10.34" }
solana-rpc = { path = "../rpc", version = "=1.10.34" }
safecoin-sdk = { path = "../sdk", version = "=1.10.34" }
safecoin-streamer = { path = "../streamer", version = "=1.10.34" }
safecoin-test-validator = { path = "../test-validator", version = "=1.10.34" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.10.34" }
tokio = { version = "~1.14.1", features = ["full"] }

[dev-dependencies]
safecoin-logger = { path = "../logger", version = "=1.10.34" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
