[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "safecoin-ledger-tool"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.10.34"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-ledger-tool"

[dependencies]
bs58 = "0.4.0"
clap = "2.33.1"
crossbeam-channel = "0.5"
csv = "1.1.6"
dashmap = "4.0.2"
histogram = "0.6.9"
itertools = "0.10.3"
log = { version = "0.4.14" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
safecoin-clap-utils = { path = "../clap-utils", version = "=1.10.34" }
safecoin-cli-output = { path = "../cli-output", version = "=1.10.34" }
safecoin-core = { path = "../core", version = "=1.10.34" }
solana-entry = { path = "../entry", version = "=1.10.34" }
safecoin-ledger = { path = "../ledger", version = "=1.10.34" }
safecoin-logger = { path = "../logger", version = "=1.10.34" }
safecoin-measure = { path = "../measure", version = "=1.10.34" }
safecoin-runtime = { path = "../runtime", version = "=1.10.34" }
safecoin-sdk = { path = "../sdk", version = "=1.10.34" }
safecoin-stake-program = { path = "../programs/stake", version = "=1.10.34" }
safecoin-storage-bigtable = { path = "../storage-bigtable", version = "=1.10.34" }
safecoin-transaction-status = { path = "../transaction-status", version = "=1.10.34" }
safecoin-version = { path = "../version", version = "=1.10.34" }
safecoin-vote-program = { path = "../programs/vote", version = "=1.10.34" }
tokio = { version = "~1.14.1", features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { package = "tikv-jemallocator", version = "0.4.1", features = ["unprefixed_malloc_on_supported_platforms"] }

[dev-dependencies]
assert_cmd = "2.0"
bytecount = "0.6.2"

[target."cfg(unix)".dependencies]
signal-hook = "0.3.13"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
