[package]
name = "solana-bpf-rust-simulation"
version = "1.10.34"
description = "Safecoin BPF Program Simulation Differences"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/solana-bpf-rust-simulation"
edition = "2021"

[features]
test-bpf = []

[dependencies]
safecoin-program = { path = "../../../../sdk/program", version = "=1.10.34" }

[dev-dependencies]
safecoin-logger = { path = "../../../../logger", version = "=1.10.34" }
safecoin-program-test = { path = "../../../../program-test", version = "=1.10.34" }
safecoin-sdk = { path = "../../../../sdk", version = "=1.10.34" }
safecoin-validator = { path = "../../../../validator", version = "=1.10.34" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
