[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-dos"
version = "1.6.20"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
bincode = "1.3.1"
clap = "2.33.1"
log = "0.4.11"
rand = "0.7.0"
rayon = "1.5.0"
safecoin-clap-utils = { path = "../clap-utils", version = "=1.6.20" }
safecoin-core = { path = "../core", version = "=1.6.20" }
safecoin-ledger = { path = "../ledger", version = "=1.6.20" }
safecoin-logger = { path = "../logger", version = "=1.6.20" }
safecoin-net-utils = { path = "../net-utils", version = "=1.6.20" }
safecoin-runtime = { path = "../runtime", version = "=1.6.20" }
safecoin-sdk = { path = "../sdk", version = "=1.6.20" }
safecoin-version = { path = "../version", version = "=1.6.20" }
safecoin-client = { path = "../client", version = "=1.6.20" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
