[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "safecoin-dos"
version = "1.9.29"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
bincode = "1.3.3"
clap = "2.33.1"
log = "0.4.14"
rand = "0.7.0"
safecoin-core = { path = "../core", version = "=1.9.29" }
safecoin-gossip = { path = "../gossip", version = "=1.9.29" }
safecoin-logger = { path = "../logger", version = "=1.9.29" }
safecoin-net-utils = { path = "../net-utils", version = "=1.9.29" }
safecoin-perf = { path = "../perf", version = "=1.9.29" }
safecoin-sdk = { path = "../sdk", version = "=1.9.29" }
safecoin-streamer = { path = "../streamer", version = "=1.9.29" }
safecoin-version = { path = "../version", version = "=1.9.29" }
safecoin-client = { path = "../client", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
