[package]
name = "safecoin-bpf-programs"
description = "Safecoin: Enterprise Security for the Community by the Community"
version = "1.10.32"
documentation = "https://docs.rs/solana"
homepage = "https://safecoin.org/"
readme = "README.md"
repository = "https://github.com/fair-exchange/safecoin"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
bpf_c = []
bpf_rust = []

[build-dependencies]
walkdir = "2"

[dependencies]
bincode = "1.1.4"
byteorder = "1.3.2"
elf = "0.0.10"
itertools = "0.10.1"
log = "0.4.11"
miow = "0.3.6"
net2 = "0.2.37"
solana-bpf-rust-invoke = { path = "rust/invoke", version = "=1.10.32"}
safecoin-bpf-loader-program = { path = "../bpf_loader", version = "=1.10.32"}
solana-bpf-rust-realloc = { path = "rust/realloc", version = "=1.10.32"}
solana-bpf-rust-realloc-invoke = { path = "rust/realloc_invoke", version = "=1.10.32"}
safecoin-cli-output = { path = "../../cli-output", version = "=1.10.32" }
safecoin-logger = { path = "../../logger", version = "=1.10.32" }
safecoin-measure = { path = "../../measure", version = "=1.10.32" }
solana_rbpf = "=0.2.24"
safecoin-runtime = { path = "../../runtime", version = "=1.10.32" }
safecoin-program-runtime = { path = "../../program-runtime", version = "=1.10.32" }
safecoin-sdk = { path = "../../sdk", version = "=1.10.32" }
safecoin-transaction-status = { path = "../../transaction-status", version = "=1.10.32" }
safecoin-account-decoder = { path = "../../account-decoder", version = "=1.10.32" }

[[bench]]
name = "bpf_loader"

[workspace]
members = [
    "rust/128bit",
    "rust/128bit_dep",
    "rust/alloc",
    "rust/call_depth",
    "rust/caller_access",
    "rust/curve25519",
    "rust/custom_heap",
    "rust/dep_crate",
    "rust/deprecated_loader",
    "rust/dup_accounts",
    "rust/error_handling",
    "rust/log_data",
    "rust/external_spend",
    "rust/finalize",
    "rust/instruction_introspection",
    "rust/invoke",
    "rust/invoke_and_error",
    "rust/invoke_and_ok",
    "rust/invoke_and_return",
    "rust/invoked",
    "rust/iter",
    "rust/many_args",
    "rust/many_args_dep",
    "rust/mem",
    "rust/membuiltins",
    "rust/noop",
    "rust/panic",
    "rust/param_passing",
    "rust/param_passing_dep",
    "rust/rand",
    "rust/realloc",
    "rust/realloc_invoke",
    "rust/ro_modify",
    "rust/ro_account_modify",
    "rust/sanity",
    "rust/secp256k1_recover",
    "rust/sha",
    "rust/sibling_inner_instruction",
    "rust/sibling_instruction",
    "rust/simulation",
    "rust/spoof1",
    "rust/spoof1_system",
    "rust/sysvar",
    "rust/upgradeable",
    "rust/upgraded",
    "rust/zk_token_elgamal",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
