[package]
name = "safecoin-send-transaction-service"
version = "1.14.3"
description = "Safecoin send transaction service"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-send-transaction-service"
license = "Apache-2.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
log = "0.4.17"
safecoin-client = { path = "../client", version = "=1.14.3" }
safecoin-measure = { path = "../measure", version = "=1.14.3" }
safecoin-metrics = { path = "../metrics", version = "=1.14.3" }
safecoin-runtime = { path = "../runtime", version = "=1.14.3" }
safecoin-sdk = { path = "../sdk", version = "=1.14.3" }

[dev-dependencies]
safecoin-logger = { path = "../logger", version = "=1.14.3" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
