[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-store-tool"
description = "Tool to inspect append vecs"
version = "1.8.12"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
log = { version = "0.4.11" }
safecoin-logger = { path = "../../logger", version = "=1.8.12" }
safecoin-version = { path = "../../version", version = "=1.8.12" }
safecoin-measure = { path = "../../measure", version = "=1.8.12" }
safecoin-runtime = { path = "..", version = "=1.8.12" }
safecoin-sdk = { path = "../../sdk", version = "=1.8.12" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
