[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "safecoin-store-tool"
description = "Tool to inspect append vecs"
version = "1.9.29"
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
publish = false

[dependencies]
log = { version = "0.4.14" }
safecoin-logger = { path = "../../logger", version = "=1.9.29" }
safecoin-version = { path = "../../version", version = "=1.9.29" }
safecoin-runtime = { path = "..", version = "=1.9.29" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
