[package]
name = "solana-poh"
version = "1.8.12"
description = "Safecoin PoH"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/solana-poh"
edition = "2018"

[dependencies]
core_affinity = "0.5.10"
crossbeam-channel = "0.4"
log = "0.4.11"
safecoin-ledger = { path = "../ledger", version = "=1.8.12" }
safecoin-measure = { path = "../measure", version = "=1.8.12" }
safecoin-metrics = { path = "../metrics", version = "=1.8.12" }
safecoin-runtime = { path = "../runtime", version = "=1.8.12" }
safecoin-sdk = { path = "../sdk", version = "=1.8.12" }
safecoin-sys-tuner = { path = "../sys-tuner", version = "=1.8.12" }
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.1"
matches = "0.1.6"
rand = "0.7.0"
safecoin-logger = { path = "../logger", version = "=1.8.12" }
safecoin-perf = { path = "../perf", version = "=1.8.12" }

[lib]
crate-type = ["lib"]
name = "solana_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
