[package]
name = "safecoin-poh"
version = "1.14.17"
description = "Safecoin PoH"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-poh"
edition = "2021"

[dependencies]
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
log = "0.4.17"
safecoin-entry = { path = "../entry", version = "=1.14.17" }
safecoin-ledger = { path = "../ledger", version = "=1.14.17" }
safecoin-measure = { path = "../measure", version = "=1.14.17" }
safecoin-metrics = { path = "../metrics", version = "=1.14.17" }
safecoin-runtime = { path = "../runtime", version = "=1.14.17" }
safecoin-sdk = { path = "../sdk", version = "=1.14.17" }
safecoin-sys-tuner = { path = "../sys-tuner", version = "=1.14.17" }
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
matches = "0.1.9"
rand = "0.7.0"
safecoin-logger = { path = "../logger", version = "=1.14.17" }
safecoin-perf = { path = "../perf", version = "=1.14.17" }

[lib]
crate-type = ["lib"]
name = "safecoin_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
