[package]
name = "safecoin-vote-program"
version = "1.14.17"
description = "Safecoin Vote program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-vote-program"
edition = "2021"

[dependencies]
bincode = "1.3.3"
log = "0.4.17"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.138"
serde_derive = "1.0.103"
safecoin-frozen-abi = { path = "../../frozen-abi", version = "=1.14.17" }
safecoin-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.14.17" }
safecoin-metrics = { path = "../../metrics", version = "=1.14.17" }
safecoin-program-runtime = { path = "../../program-runtime", version = "=1.14.17" }
safecoin-sdk = { path = "../../sdk", version = "=1.14.17" }
thiserror = "1.0"

[dev-dependencies]
itertools = "0.10.3"
rand = "0.7.0"
safecoin-logger = { path = "../../logger", version = "=1.14.17" }
test-case = "2.1.0"

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "solana_vote_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
