[package]
name = "safecoin-metrics"
version = "1.10.34"
description = "Safecoin Metrics"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
documentation = "https://docs.rs/safecoin-metrics"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
gethostname = "0.2.3"
lazy_static = "1.4.0"
log = "0.4.14"
reqwest = { version = "0.11.10", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
safecoin-sdk = { path = "../sdk", version = "=1.10.34" }

[dev-dependencies]
env_logger = "0.9.0"
rand = "0.7.0"
serial_test = "0.6.0"

[lib]
name = "solana_metrics"

[[bench]]
name = "metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
